version: "3.1"

services:

  # laravel application
  app:
    restart: always
    tmpfs:
      - /var/www/html/storage/framework/cache
    volumes:
      # /etc
      - ./services/app/etc/php7/conf.d/70-php.ini:/etc/php7/conf.d/70-php.ini:ro
      # /var
      - ./services/app/var/log/nginx:/var/log/nginx
      - ./services/app/var/www/html:/var/www/html
    environment:
      APP_TIMEZONE: ${TIMEZONE}
      APP_UID: ${APP_UID}
      APP_GID: ${APP_GID}
      WAIT_HOSTS: db:3306
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      MAIL_DRIVER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 25
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
    depends_on:
      - db
    ports:
      - ${APP_PORT}:80


  # database server
  db:
    image: mariadb:10.2
    restart: always
    volumes:
      # etc
      - ./services/db/etc/mysql/conf.d/:/app_etc/mysql/conf.d/
      # var
      - ./services/db/var/lib/mysql:/var/lib/mysql
    environment:
      TZ: ${TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306

networks:
  default: